name: msbuild

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: MSBuild
        run: |
          cmake -B build -S .
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: my-exe
          path: build/**/*.exe
