name: Build Windows EXE

on:
  push:
    branches: [ master ]
  # Разрешает ручной запуск из интерфейса GitHub
  workflow_dispatch:

jobs:
  build:
    # Используем среду Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup vcpkg
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
        shell: powershell

      - name: Install Static Dependencies (xlsxio)
        run: |
          # ИСПОЛЬЗУЕМ СТАТИЧЕСКИЙ ТРИПЛЕТ
          .\vcpkg\vcpkg install xlsxio:x64-windows-static
        shell: powershell

      - name: Configure CMake
        run: cmake -B build -S . `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
        shell: powershell

      - name: Build
        run: cmake --build build --config Release
        shell: powershell

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-exe
          path: build/Release/MyApp.exe
