name: Build Windows EXE

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download xlsxio
        run: |
          git clone --depth=1 https://github.com/brechtsanders/xlsxio.git
          cd xlsxio
          if (Test-Path build) { Remove-Item -Recurse -Force build }
          New-Item -ItemType Directory -Name build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/xlsxio-install"
          cmake --build . --config Release
          cmake --install . --prefix "${{ github.workspace }}/xlsxio-install"
        shell: powershell

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{ github.workspace }}/xlsxio-install"
        shell: powershell

      - name: Build
        run: cmake --build build --config Release
        shell: powershell

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-exe
          path: build/**/*.exe

