name: Build Windows EXE

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Клонируем проект
      - uses: actions/checkout@v4

      # 2. Скачиваем и билдим vcpkg
      - name: Setup vcpkg
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
        shell: powershell

      # 3. Устанавливаем xlsxio и зависимости (x64)
      - name: Install dependencies
        run: |
          .\vcpkg\vcpkg install xlsxio:x64-windows
        shell: powershell

      # 4. Конфигурируем CMake с toolchain vcpkg и архитектурой x64
      - name: Configure CMake
        run: cmake -B build -S . `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake `
            -A x64
        shell: powershell

      # 5. Сборка проекта
      - name: Build
        run: cmake --build build --config Release
        shell: powershell

      # 6. Загружаем .exe как артефакт
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-exe
          path: build/Release/*.exe

